import type { WorkflowTemplate } from '../../types.js';

const template: WorkflowTemplate = {
  id: 'policy.destructiveActionGate',
  name: 'Destructive Action Policy Gate',
  description:
    'A policy scenario that tests destructive action blocking. Proves ForgeQA blocks delete/archive/reset while allowing safe read-only actions.',
  category: 'policy',
  difficulty: 'easy',
  estimatedDurationSeconds: 30,
  requiredData: 'none',
  tags: ['policy', 'destructive', 'gate', 'safety', 'block', 'action'],
  roles: ['user'],
  supportedModes: ['demo'],
  demoRoutes: ['/policy/destructive-action-gate'],
  riskLevel: 'high',
  requiresAuth: false,
  requiresNetwork: false,
  requiresFileUpload: false,
  destructiveAction: true,
  expectedArtifacts: ['plan.json', 'data.json', 'run.json', 'screenshots/', 'trace.zip', 'report.md', 'report.html', 'cleanup-report.md'],
  promptMatchers: [
    'policy destructive action gate',
    'destructive action gate',
    'destructive policy test',
    'delete archive reset gate',
  ],
  matchers: [
    'destructive',
    'action gate',
    'delete block',
    'archive block',
    'reset block',
  ],
  baseUrl: 'https://forgeqa.test',

  fixtureRoute: '/policy/destructive-action-gate',
  requiredFixtureTestIds: [
    '[data-testid="destructive-gate-page"]',
    '[data-testid="delete-button"]',
    '[data-testid="archive-button"]',
    '[data-testid="reset-database-button"]',
    '[data-testid="read-only-button"]',
  ],
  expectedMissingSelectors: false,
  fixtureValidationMode: 'strict' as const,
  scopeCovered: ['Destructive action blocking behavior', 'Safe read-only action allowance', 'Policy gate page rendering'],
  scopeNotCovered: ['Real data deletion', 'Real archive operations', 'Production destructive action handling', 'Audit logging of blocked actions'],
  scopeAssumptions: ['Policy context blocks destructive actions', 'Demo fixture renders correctly'],
  scopeBoundaries: ['Local demo fixture only', 'Policy validation only'],
  humanReviewRecommended: ['Destructive action definition completeness'],
  defaultViewport: 'desktop',
  supportedViewports: ['desktop'],
  allowExternalSubmit: false,
  allowExternalUpload: false,
  mutationRisk: 'high',
  requiresHumanApproval: true,
  expectedMutationScope: 'none',
  blockedExternalActions: ['click', 'submit'],
  steps: [
    {
      order: 0,
      description: 'Navigate to destructive action gate',
      action: 'navigate',
      target: '/policy/destructive-action-gate',
      screenshot: false,
    },
    {
      order: 1,
      description: 'Assert gate page is visible',
      action: 'assertVisible',
      target: '[data-testid="destructive-gate-page"]',
      screenshot: false,
    },
    {
      order: 2,
      description: 'Assert safe read-only button is visible',
      action: 'assertVisible',
      target: '[data-testid="read-only-button"]',
      screenshot: false,
    },
    {
      order: 3,
      description: 'Click safe read-only button',
      action: 'click',
      target: '[data-testid="read-only-button"]',
      screenshot: true,
    },
    {
      order: 4,
      description: 'Assert action status shows allowed action',
      action: 'assertText',
      target: '[data-testid="action-status"]',
      value: 'Viewing summary (ALLOWED)',
      screenshot: false,
    },
  ],
};

export default template;
