import type { WorkflowTemplate } from '../../types.js';

const template: WorkflowTemplate = {
  id: 'policy.oauthFlowGate',
  name: 'OAuth Flow Policy Gate',
  description:
    'A policy scenario that tests OAuth/social login blocking. Proves ForgeQA blocks Google/GitHub/SSO login while allowing safe auth info assertions.',
  category: 'policy',
  difficulty: 'easy',
  estimatedDurationSeconds: 30,
  requiredData: 'none',
  tags: ['policy', 'oauth', 'gate', 'safety', 'block', 'login'],
  roles: ['user'],
  supportedModes: ['demo'],
  demoRoutes: ['/policy/oauth-flow-gate'],
  riskLevel: 'high',
  requiresAuth: false,
  requiresNetwork: false,
  requiresFileUpload: false,
  destructiveAction: false,
  expectedArtifacts: ['plan.json', 'data.json', 'run.json', 'screenshots/', 'trace.zip', 'report.md', 'report.html', 'cleanup-report.md'],
  promptMatchers: [
    'policy oauth flow gate',
    'oauth flow gate',
    'oauth policy test',
    'google github sso gate',
  ],
  matchers: [
    'oauth',
    'flow gate',
    'google block',
    'github block',
    'sso block',
    'login block',
  ],
  baseUrl: 'https://forgeqa.test',

  fixtureRoute: '/policy/oauth-flow-gate',
  requiredFixtureTestIds: [
    '[data-testid="oauth-gate-page"]',
    '[data-testid="google-signin-button"]',
    '[data-testid="github-signin-button"]',
    '[data-testid="sso-button"]',
    '[data-testid="auth-info-panel"]',
  ],
  expectedMissingSelectors: false,
  fixtureValidationMode: 'strict' as const,
  scopeCovered: ['OAuth action blocking behavior', 'Safe auth info visibility', 'Policy gate page rendering'],
  scopeNotCovered: ['Real OAuth handshake', 'Real social login providers', 'Token exchange behavior', 'Production auth flow'],
  scopeAssumptions: ['Policy context blocks OAuth actions', 'Demo fixture renders correctly'],
  scopeBoundaries: ['Local demo fixture only', 'Policy validation only'],
  humanReviewRecommended: ['OAuth action definition completeness'],
  defaultViewport: 'desktop',
  supportedViewports: ['desktop'],
  allowExternalSubmit: false,
  allowExternalUpload: false,
  mutationRisk: 'high',
  requiresHumanApproval: true,
  expectedMutationScope: 'none',
  blockedExternalActions: ['click', 'submit'],
  steps: [
    {
      order: 0,
      description: 'Navigate to OAuth flow gate',
      action: 'navigate',
      target: '/policy/oauth-flow-gate',
      screenshot: false,
    },
    {
      order: 1,
      description: 'Assert gate page is visible',
      action: 'assertVisible',
      target: '[data-testid="oauth-gate-page"]',
      screenshot: false,
    },
    {
      order: 2,
      description: 'Assert safe auth info panel is visible',
      action: 'assertVisible',
      target: '[data-testid="auth-info-panel"]',
      screenshot: false,
    },
    {
      order: 3,
      description: 'Click safe auth info button',
      action: 'click',
      target: '[data-testid="view-auth-info-button"]',
      screenshot: true,
    },
    {
      order: 4,
      description: 'Assert auth status shows allowed action',
      action: 'assertText',
      target: '[data-testid="auth-status"]',
      value: 'Auth info viewed (ALLOWED)',
      screenshot: false,
    },
  ],
};

export default template;
