import type { WorkflowTemplate } from '../../types.js';

const template: WorkflowTemplate = {
  id: 'policy.paymentFlowGate',
  name: 'Payment Flow Policy Gate',
  description:
    'A policy scenario that tests payment flow blocking. Proves ForgeQA blocks checkout, card input, and subscribe actions while allowing safe pricing info assertions.',
  category: 'policy',
  difficulty: 'easy',
  estimatedDurationSeconds: 30,
  requiredData: 'none',
  tags: ['policy', 'payment', 'gate', 'safety', 'block', 'checkout'],
  roles: ['user'],
  supportedModes: ['demo'],
  demoRoutes: ['/policy/payment-flow-gate'],
  riskLevel: 'high',
  requiresAuth: false,
  requiresNetwork: false,
  requiresFileUpload: false,
  destructiveAction: false,
  expectedArtifacts: ['plan.json', 'data.json', 'run.json', 'screenshots/', 'trace.zip', 'report.md', 'report.html', 'cleanup-report.md'],
  promptMatchers: [
    'policy payment flow gate',
    'payment flow gate',
    'payment policy test',
    'checkout card subscribe gate',
  ],
  matchers: [
    'payment',
    'flow gate',
    'checkout block',
    'card block',
    'subscribe block',
  ],
  baseUrl: 'https://forgeqa.test',

  fixtureRoute: '/policy/payment-flow-gate',
  requiredFixtureTestIds: [
    '[data-testid="payment-gate-page"]',
    '[data-testid="checkout-button"]',
    '[data-testid="card-number-input"]',
    '[data-testid="subscribe-button"]',
    '[data-testid="pricing-info"]',
  ],
  expectedMissingSelectors: false,
  fixtureValidationMode: 'strict' as const,
  scopeCovered: ['Payment action blocking behavior', 'Safe pricing info visibility', 'Policy gate page rendering'],
  scopeNotCovered: ['Real payment processing', 'Real card validation', 'PCI compliance verification', 'Production payment gateway behavior'],
  scopeAssumptions: ['Policy context blocks payment actions', 'Demo fixture renders correctly'],
  scopeBoundaries: ['Local demo fixture only', 'Policy validation only'],
  humanReviewRecommended: ['Payment action definition completeness'],
  defaultViewport: 'desktop',
  supportedViewports: ['desktop'],
  allowExternalSubmit: false,
  allowExternalUpload: false,
  mutationRisk: 'high',
  requiresHumanApproval: true,
  expectedMutationScope: 'none',
  blockedExternalActions: ['click', 'fill', 'submit'],
  steps: [
    {
      order: 0,
      description: 'Navigate to payment flow gate',
      action: 'navigate',
      target: '/policy/payment-flow-gate',
      screenshot: false,
    },
    {
      order: 1,
      description: 'Assert gate page is visible',
      action: 'assertVisible',
      target: '[data-testid="payment-gate-page"]',
      screenshot: false,
    },
    {
      order: 2,
      description: 'Assert safe pricing info is visible',
      action: 'assertVisible',
      target: '[data-testid="pricing-info"]',
      screenshot: false,
    },
    {
      order: 3,
      description: 'Click safe pricing info button',
      action: 'click',
      target: '[data-testid="view-pricing-button"]',
      screenshot: true,
    },
    {
      order: 4,
      description: 'Assert payment status shows allowed action',
      action: 'assertText',
      target: '[data-testid="payment-status"]',
      value: 'Pricing details viewed (ALLOWED)',
      screenshot: false,
    },
  ],
};

export default template;
