import type { WorkflowTemplate } from '../types.js';

const template: WorkflowTemplate = {
  id: 'forgecircle.registerAlumniCompleteProfile',
  name: 'Register Alumni, Complete Profile, Upload Avatar',
  description:
    'End-to-end alumni registration flow: sign up, complete profile fields, and upload an avatar image.',
  category: 'registration',
  difficulty: 'medium',
  estimatedDurationSeconds: 120,
  requiredData: 'users_and_files',
  tags: ['registration', 'profile', 'upload', 'form', 'alumni'],
  roles: ['alumni'],
  supportedModes: ['demo'],
  allowExternalSubmit: false,
  allowExternalUpload: false,
  demoRoutes: ['/register/alumni'],
  riskLevel: 'low',
  requiresAuth: false,
  requiresNetwork: false,
  requiresFileUpload: true,
  destructiveAction: false,
  expectedArtifacts: ['plan.json', 'data.json', 'run.json', 'screenshots/', 'trace.zip', 'report.md', 'report.html', 'cleanup-report.md'],
  promptMatchers: [
    'register alumni complete profile upload avatar',
    'alumni registration with profile and avatar',
    'register as alumni and upload avatar',
  ],
  matchers: [
    'register alumni',
    'complete profile',
    'upload avatar',
    'alumni registration',
  ],
  baseUrl: 'https://forgecircle.test',

  fixtureRoute: '/register/alumni',
  requiredFixtureTestIds: ['[data-testid="registration-form"]', '[data-testid="email-input"]', '[data-testid="password-input"]', '[data-testid="full-name-input"]', '[data-testid="register-submit"]'],
  expectedMissingSelectors: false,
  fixtureValidationMode: 'strict' as const,
  scopeCovered: ['Registration form loads', 'Email input accepts test data', 'Password input accepts test data', 'Name input accepts test data', 'Form submission navigates to profile', 'Profile page loads', 'Avatar upload input accepts file', 'Department and batch fields accept input', 'Profile save action triggers confirmation'],
  scopeNotCovered: ['Real email delivery', 'Backend user persistence', 'Password strength validation rules', 'Duplicate email handling', 'Session management', 'Real avatar storage'],
  scopeAssumptions: ['Demo fixture renders correctly', 'Form fields use data-testid attributes'],
  scopeBoundaries: ['Local demo server only', 'Generated test data only'],
  humanReviewRecommended: ['Avatar upload UX on mobile', 'Form accessibility'],
  defaultViewport: 'desktop',
  supportedViewports: ['desktop', 'mobile', 'tablet'],
  steps: [
    {
      order: 0,
      description: 'Navigate to alumni registration page',
      action: 'navigate',
      target: '/register/alumni',
      screenshot: true,
    },
    {
      order: 1,
      description: 'Fill registration email',
      action: 'fill',
      target: '[data-testid="email-input"]',
      screenshot: false,
    },
    {
      order: 2,
      description: 'Fill registration password',
      action: 'fill',
      target: '[data-testid="password-input"]',
      screenshot: false,
    },
    {
      order: 3,
      description: 'Fill full name',
      action: 'fill',
      target: '[data-testid="full-name-input"]',
      screenshot: false,
    },
    {
      order: 4,
      description: 'Submit registration form',
      action: 'click',
      target: '[data-testid="register-submit"]',
      screenshot: true,
    },
    {
      order: 5,
      description: 'Wait for redirect to profile',
      action: 'wait',
      value: '2000',
      screenshot: false,
    },
    {
      order: 6,
      description: 'Assert on profile page',
      action: 'assertVisible',
      target: '[data-testid="profile-page"]',
      screenshot: true,
    },
    {
      order: 7,
      description: 'Fill department field',
      action: 'fill',
      target: '[data-testid="department-input"]',
      screenshot: false,
    },
    {
      order: 8,
      description: 'Fill batch field',
      action: 'fill',
      target: '[data-testid="batch-input"]',
      screenshot: false,
    },
    {
      order: 9,
      description: 'Upload avatar image',
      action: 'upload',
      target: '[data-testid="avatar-upload"]',
      screenshot: true,
    },
    {
      order: 10,
      description: 'Save profile changes',
      action: 'click',
      target: '[data-testid="profile-save"]',
      screenshot: true,
    },
    {
      order: 11,
      description: 'Assert success message visible',
      action: 'assertVisible',
      target: '[data-testid="profile-saved"]',
      screenshot: true,
    },
  ],
};

export default template;
