import type { WorkflowTemplate } from '../types.js';

const template: WorkflowTemplate = {
  id: 'generic.externalSafeSubmit',
  name: 'External Safe Submit',
  description:
    'A low-risk external submit test that safely fills and submits a local fixture form. Proves approved external mutation is possible under strict controls.',
  category: 'policy',
  difficulty: 'easy',
  estimatedDurationSeconds: 45,
  requiredData: 'users',
  tags: ['external', 'submit', 'policy', 'safe', 'local', 'form', 'approved'],
  roles: ['user'],
  supportedModes: ['demo', 'external'],
  demoRoutes: ['/external-safe/submit-form'],
  riskLevel: 'low',
  requiresAuth: false,
  requiresNetwork: false,
  requiresFileUpload: false,
  destructiveAction: false,
  expectedArtifacts: ['plan.json', 'data.json', 'run.json', 'screenshots/', 'trace.zip', 'report.md', 'report.html', 'cleanup-report.md'],
  promptMatchers: [
    'external safe submit',
    'safe external submit',
    'local submit form',
    'approved submit form',
    'external submit policy test',
  ],
  matchers: [
    'external safe',
    'safe submit',
    'local submit',
    'approved submit',
    'external policy test',
  ],
  baseUrl: 'https://forgeqa.test',

  fixtureRoute: '/external-safe/submit-form',
  requiredFixtureTestIds: ['[data-testid="external-safe-page"]', '[data-testid="search-query-input"]', '[data-testid="safe-submit-button"]', '[data-testid="safe-submit-status"]', '[data-testid="safe-submit-form"]'],
  expectedMissingSelectors: false,
  fixtureValidationMode: 'strict' as const,
  scopeCovered: ['Safe local/staging submit gate', 'Approval-required submit execution', 'Policy evidence capture'],
  scopeNotCovered: ['Production submission', 'Real backend persistence', 'Payment/email/OAuth flows', 'Cross-domain behavior'],
  scopeAssumptions: ['Demo fixture renders correctly', 'Policy context is configured'],
  scopeBoundaries: ['Local demo server only', 'Approved actions only'],
  humanReviewRecommended: ['Policy strictness appropriateness'],
  defaultViewport: 'desktop',
  supportedViewports: ['desktop', 'mobile', 'tablet'],
  allowExternalSubmit: true,
  allowExternalUpload: false,
  mutationRisk: 'low',
  requiresHumanApproval: true,
  expectedMutationScope: 'local_only',
  steps: [
    {
      order: 0,
      description: 'Navigate to external safe submit form',
      action: 'navigate',
      target: '/external-safe/submit-form',
      screenshot: false,
    },
    {
      order: 1,
      description: 'Assert safe submit page is visible',
      action: 'assertVisible',
      target: '[data-testid="external-safe-page"]',
      screenshot: false,
    },
    {
      order: 2,
      description: 'Fill search query input with generated data',
      action: 'fill',
      target: '[data-testid="search-query-input"]',
      screenshot: false,
    },
    {
      order: 3,
      description: 'Click safe submit button',
      action: 'click',
      target: '[data-testid="safe-submit-button"]',
      screenshot: true,
    },
    {
      order: 4,
      description: 'Assert status text shows safe submit confirmation',
      action: 'assertText',
      target: '[data-testid="safe-submit-status"]',
      value: 'Submitted safely for local test',
      screenshot: false,
    },
    {
      order: 5,
      description: 'Wait briefly for visual stability',
      action: 'wait',
      value: '500',
      screenshot: false,
    },
  ],
};

export default template;
