import type { WorkflowTemplate } from '../types.js';

const template: WorkflowTemplate = {
  id: 'policy.externalRiskForm',
  name: 'External Risk Form — Policy Test',
  description:
    'Intentionally triggers all execution policy gates to verify blocking, caution, and safe actions.',
  category: 'policy',
  difficulty: 'easy',
  estimatedDurationSeconds: 45,
  requiredData: 'users',
  tags: ['policy', 'external', 'risk', 'blocked', 'safety', 'gates'],
  roles: ['user'],
  supportedModes: ['demo', 'external'],
  demoRoutes: ['/policy/external-risk-form'],
  riskLevel: 'medium',
  requiresAuth: false,
  requiresNetwork: false,
  requiresFileUpload: false,
  destructiveAction: false,
  expectedArtifacts: ['plan.json', 'data.json', 'run.json', 'screenshots/', 'trace.zip', 'report.md', 'report.html', 'cleanup-report.md'],
  promptMatchers: [
    'external risk form',
    'policy test',
    'safety gate test',
  ],
  matchers: [
    'external risk',
    'policy gate',
    'safety test',
  ],
  baseUrl: 'https://forgeqa.test',

  fixtureRoute: '/policy/external-risk-form',
  requiredFixtureTestIds: ['[data-testid="search-input"]', '[data-testid="safe-btn"]', '[data-testid="submit-btn"]', '[data-testid="delete-btn"]', '[data-testid="pay-btn"]', '[data-testid="send-btn"]', '[data-testid="password-input"]', '[data-testid="status-box"]'],
  expectedMissingSelectors: false,
  fixtureValidationMode: 'strict' as const,
  scopeCovered: ['Policy gate behavior for safe actions', 'Policy gate behavior for submit actions', 'Policy gate behavior for delete actions', 'Policy gate behavior for payment actions', 'Policy gate behavior for email actions', 'Policy gate behavior for credential fields'],
  scopeNotCovered: ['Real payment processing', 'Real email sending', 'Real backend mutations', 'Production policy enforcement'],
  scopeAssumptions: ['Policy context is configured correctly', 'Demo fixture renders correctly'],
  scopeBoundaries: ['Local demo fixture only', 'Policy validation only'],
  humanReviewRecommended: ['Policy strictness appropriateness'],
  defaultViewport: 'desktop',
  allowExternalSubmit: true,
  allowExternalUpload: false,
  mutationRisk: 'medium',
  expectedMutationScope: 'generated_data_only',
  steps: [
    {
      order: 0,
      description: 'Navigate to external risk form',
      action: 'navigate',
      screenshot: false,
      target: '/policy/external-risk-form',
    },
    {
      order: 1,
      description: 'Fill search input with generated data',
      action: 'fill',
      screenshot: false,
      target: '[data-testid="search-input"]',
    },
    {
      order: 2,
      description: 'Click safe action button',
      action: 'click',
      screenshot: false,
      target: '[data-testid="safe-btn"]',
    },
    {
      order: 3,
      description: 'Click submit registration button',
      action: 'click',
      screenshot: false,
      target: '[data-testid="submit-btn"]',
      continueOnFailure: true,
    },
    {
      order: 4,
      description: 'Click delete user button',
      action: 'click',
      screenshot: false,
      target: '[data-testid="delete-btn"]',
      continueOnFailure: true,
    },
    {
      order: 5,
      description: 'Click checkout pay button',
      action: 'click',
      screenshot: false,
      target: '[data-testid="pay-btn"]',
      continueOnFailure: true,
    },
    {
      order: 6,
      description: 'Click send invite button',
      action: 'click',
      screenshot: false,
      target: '[data-testid="send-btn"]',
      continueOnFailure: true,
    },
    {
      order: 7,
      description: 'Fill password credential field',
      action: 'fill',
      screenshot: false,
      target: '[data-testid="password-input"]',
      continueOnFailure: true,
    },
    {
      order: 8,
      description: 'Assert status box shows expected text',
      action: 'assertText',
      screenshot: false,
      target: '[data-testid="status-box"]',
      value: 'Status:',
    },
  ],
};

export default template;
