import type { WorkflowTemplate } from '../types.js';

const template: WorkflowTemplate = {
  id: 'generic.mobileResponsiveCheck',
  name: 'Mobile Responsive Check',
  description:
    'Test a core page under mobile viewport size to verify responsive layout and mobile-specific UI elements.',
  category: 'responsive',
  difficulty: 'easy',
  estimatedDurationSeconds: 45,
  requiredData: 'none',
  tags: ['responsive', 'mobile', 'layout', 'viewport'],
  roles: ['user'],
  supportedModes: ['demo', 'external'],
  demoRoutes: ['/responsive'],
  riskLevel: 'low',
  mutationRisk: 'low',
  allowExternalSubmit: false,
  allowExternalUpload: false,
  expectedMutationScope: 'none',
  requiresAuth: false,
  requiresNetwork: false,
  requiresFileUpload: false,
  destructiveAction: false,
  expectedArtifacts: ['plan.json', 'data.json', 'run.json', 'screenshots/', 'trace.zip', 'report.md', 'report.html', 'cleanup-report.md'],
  promptMatchers: [
    'mobile responsive',
    'responsive check',
    'mobile layout',
    'check mobile view',
  ],
  matchers: [
    'mobile responsive',
    'responsive',
    'mobile layout',
    'mobile view',
  ],
  baseUrl: 'https://forgeqa.test',

  fixtureRoute: '/responsive',
  requiredFixtureTestIds: ['[data-testid="responsive-page"]'],
  expectedMissingSelectors: false,
  fixtureValidationMode: 'strict' as const,
  scopeCovered: ['Page renders at mobile viewport', 'Navigation adapts to mobile', 'Touch-friendly elements visible'],
  scopeNotCovered: ['Real device testing', 'Touch gesture handling', 'Orientation change behavior', 'Performance on slow networks'],
  scopeAssumptions: ['Playwright mobile emulation is sufficient'],
  scopeBoundaries: ['Emulated viewport only'],
  humanReviewRecommended: ['Real device verification recommended'],
  defaultViewport: 'mobile',
  supportedViewports: ['mobile', 'small-mobile', 'tablet'],
  responsiveAssertions: true,
  steps: [
    {
      order: 0,
      description: 'Navigate to responsive test page',
      action: 'navigate',
      target: '/responsive',
      screenshot: true,
    },
    {
      order: 1,
      description: 'Assert responsive page wrapper visible',
      action: 'assertVisible',
      target: '[data-testid="responsive-page"]',
      screenshot: true,
    },
    {
      order: 2,
      description: 'Assert mobile nav visible',
      action: 'assertVisible',
      target: '[data-testid="mobile-nav"]',
      screenshot: true,
    },
    {
      order: 3,
      description: 'Assert desktop nav hidden',
      action: 'assertHidden',
      target: '[data-testid="desktop-nav"]',
      screenshot: true,
    },
    {
      order: 4,
      description: 'Assert hero section visible',
      action: 'assertVisible',
      target: '[data-testid="hero-section"]',
      screenshot: true,
    },
    {
      order: 5,
      description: 'Click mobile menu button',
      action: 'click',
      target: '[data-testid="menu-button"]',
      screenshot: true,
    },
    {
      order: 6,
      description: 'Assert menu opened',
      action: 'assertVisible',
      target: '[data-testid="menu-opened"]',
      screenshot: true,
    },
  ],
};

export default template;
