import type { WorkflowTemplate } from '../types.js';

const template: WorkflowTemplate = {
  id: 'generic.multiStepFormValidation',
  name: 'Multi-Step Form Validation',
  description:
    'Test multi-step form validation and required-field behavior across wizard-style steps.',
  category: 'form',
  difficulty: 'medium',
  estimatedDurationSeconds: 90,
  requiredData: 'users',
  tags: ['form', 'validation', 'wizard', 'required-fields', 'multi-step'],
  roles: ['user'],
  supportedModes: ['demo', 'external'],
  demoRoutes: ['/multi-step-form'],
  riskLevel: 'low',
  mutationRisk: 'medium',
  allowExternalSubmit: false,
  allowExternalUpload: false,
  expectedMutationScope: 'generated_data_only',
  requiresAuth: false,
  requiresNetwork: false,
  requiresFileUpload: false,
  destructiveAction: false,
  expectedArtifacts: ['plan.json', 'data.json', 'run.json', 'screenshots/', 'trace.zip', 'report.md', 'report.html', 'cleanup-report.md'],
  promptMatchers: [
    'multi step form',
    'form validation',
    'required fields',
    'wizard form',
  ],
  matchers: [
    'multi step',
    'form validation',
    'required field',
    'wizard',
  ],
  baseUrl: 'https://forgeqa.test',

  fixtureRoute: '/multi-step-form',
  requiredFixtureTestIds: ['[data-testid="multi-step-form"]', '[data-testid="step-1-next"]', '[data-testid="step-2-next"]'],
  expectedMissingSelectors: false,
  fixtureValidationMode: 'strict' as const,
  scopeCovered: ['Multi-step form navigation', 'Field validation on each step', 'Step progression logic', 'Final submission step'],
  scopeNotCovered: ['Server-side validation rules', 'Real data persistence', 'Error message localization'],
  scopeAssumptions: ['Demo fixture renders correctly'],
  scopeBoundaries: ['Local demo server only'],
  humanReviewRecommended: ['Validation message clarity'],
  defaultViewport: 'desktop',
  steps: [
    {
      order: 0,
      description: 'Navigate to multi-step form',
      action: 'navigate',
      target: '/multi-step-form',
      screenshot: true,
    },
    {
      order: 1,
      description: 'Submit empty form to trigger validation',
      action: 'click',
      target: '[data-testid="next-btn"]',
      screenshot: true,
    },
    {
      order: 2,
      description: 'Assert validation errors visible',
      action: 'assertVisible',
      target: '[data-testid="validation-errors"]',
      screenshot: true,
    },
    {
      order: 3,
      description: 'Fill first name',
      action: 'fill',
      target: '[data-testid="first-name-input"]',
      screenshot: false,
    },
    {
      order: 4,
      description: 'Fill last name',
      action: 'fill',
      target: '[data-testid="last-name-input"]',
      screenshot: false,
    },
    {
      order: 5,
      description: 'Fill email',
      action: 'fill',
      target: '[data-testid="email-input"]',
      screenshot: false,
    },
    {
      order: 6,
      description: 'Proceed to next step',
      action: 'click',
      target: '[data-testid="next-btn"]',
      screenshot: true,
    },
    {
      order: 7,
      description: 'Fill phone number',
      action: 'fill',
      target: '[data-testid="phone-input"]',
      screenshot: false,
    },
    {
      order: 8,
      description: 'Submit final step',
      action: 'click',
      target: '[data-testid="submit-btn"]',
      screenshot: true,
    },
    {
      order: 9,
      description: 'Assert success state visible',
      action: 'assertVisible',
      target: '[data-testid="success-message"]',
      screenshot: true,
    },
  ],
};

export default template;
