import type { WorkflowTemplate } from '../types.js';

const template: WorkflowTemplate = {
  id: 'generic.paginationAndSearch',
  name: 'Pagination and Search',
  description:
    'Test search result filtering and pagination behavior in a data table.',
  category: 'search',
  difficulty: 'medium',
  estimatedDurationSeconds: 75,
  requiredData: 'none',
  tags: ['search', 'pagination', 'table', 'filter'],
  roles: ['user'],
  supportedModes: ['demo', 'external'],
  demoRoutes: ['/search-table'],
  riskLevel: 'low',
  mutationRisk: 'none',
  allowExternalSubmit: false,
  allowExternalUpload: false,
  expectedMutationScope: 'none',
  requiresAuth: false,
  requiresNetwork: false,
  requiresFileUpload: false,
  destructiveAction: false,
  expectedArtifacts: ['plan.json', 'data.json', 'run.json', 'screenshots/', 'trace.zip', 'report.md', 'report.html', 'cleanup-report.md'],
  promptMatchers: [
    'search and pagination',
    'pagination check',
    'search filter',
    'table search',
  ],
  matchers: [
    'search',
    'pagination',
    'filter',
    'table search',
  ],
  baseUrl: 'https://forgeqa.test',

  fixtureRoute: '/search-table',
  requiredFixtureTestIds: ['[data-testid="search-input"]', '[data-testid="search-table"]'],
  expectedMissingSelectors: false,
  fixtureValidationMode: 'strict' as const,
  scopeCovered: ['Search input accepts query', 'Results table renders', 'Pagination controls visible'],
  scopeNotCovered: ['Real search backend', 'Large dataset performance', 'Filter/sort combinations'],
  scopeAssumptions: ['Demo fixture renders correctly'],
  scopeBoundaries: ['Local demo server only', 'Small dataset only'],
  humanReviewRecommended: ['Empty state handling'],
  defaultViewport: 'desktop',
  steps: [
    {
      order: 0,
      description: 'Navigate to search table page',
      action: 'navigate',
      target: '/search-table',
      screenshot: true,
    },
    {
      order: 1,
      description: 'Assert initial rows visible',
      action: 'assertVisible',
      target: '[data-testid="table-row-0"]',
      screenshot: true,
    },
    {
      order: 2,
      description: 'Search for known record',
      action: 'fill',
      target: '[data-testid="search-input"]',
      screenshot: false,
    },
    {
      order: 3,
      description: 'Trigger search',
      action: 'click',
      target: '[data-testid="search-btn"]',
      screenshot: true,
    },
    {
      order: 4,
      description: 'Assert filtered result visible',
      action: 'assertVisible',
      target: '[data-testid="search-result"]',
      screenshot: true,
    },
    {
      order: 5,
      description: 'Clear search',
      action: 'click',
      target: '[data-testid="clear-search"]',
      screenshot: true,
    },
    {
      order: 6,
      description: 'Click next page',
      action: 'click',
      target: '[data-testid="next-page"]',
      screenshot: true,
    },
    {
      order: 7,
      description: 'Assert page 2 visible',
      action: 'assertVisible',
      target: '[data-testid="page-2-indicator"]',
      screenshot: true,
    },
  ],
};

export default template;
