import type { IndustryPack } from '../types.js';

export const contentMarketingSitePack: IndustryPack = {
  id: 'content-marketing-site',
  name: 'Content / Marketing / Public Site',
  version: '1.0.0',
  description:
    'Readiness pack for public websites, landing pages, blogs, and CMS frontends. Focuses on navigation, responsive layout, forms, media accessibility, external assets, and SEO basics.',
  appCategory: 'Marketing / Content / Public Website',
  targetUsers: ['visitor', 'subscriber', 'content editor'],
  riskLevel: 'low',
  recommendedTemplates: [
    {
      templateId: 'generic.mobileResponsiveCheck',
      priority: 'required',
      reason: 'Public sites receive the majority of traffic from mobile devices.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.paginationAndSearch',
      priority: 'recommended',
      reason: 'Blogs and content sites often have search and paginated article lists.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.multiStepFormValidation',
      priority: 'recommended',
      reason: 'Contact forms, newsletter signups, and lead capture forms benefit from validation testing.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'diagnostic.mediaAccessibility',
      priority: 'required',
      reason: 'Hero images, thumbnails, and infographics must have alt text.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'diagnostic.genericTitle',
      priority: 'recommended',
      reason: 'Page titles impact SEO and should be specific, not generic.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'diagnostic.missingLabel',
      priority: 'recommended',
      reason: 'Contact and newsletter forms must have labeled inputs.',
      appliesToModes: ['both'],
    },
  ],
  optionalTemplates: [
    {
      templateId: 'generic.fileUploadWithPreview',
      priority: 'optional',
      reason: 'Relevant if the site allows user-generated content or file downloads.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'policy.destructiveActionGate',
      priority: 'optional',
      reason: 'Relevant if CMS allows content deletion.',
      appliesToModes: ['both'],
    },
  ],
  blockedTemplates: [
    'generic.alumniRegistration',
    'generic.passwordResetRequest',
  ],
  scannerFocus: [
    'navigation menu selectors and mobile hamburger menu',
    'hero section and CTA button selectors',
    'contact form labels and test IDs',
    'image alt text across the page',
    'external asset loading (fonts, analytics, CDNs)',
    'page title specificity',
    'responsive breakpoints',
  ],
  requiredScopeItems: [
    {
      id: 'cms-navigation',
      label: 'Navigation testable',
      category: 'navigation',
      required: true,
      evidenceSources: ['scan.selectorFindings', 'run.manifest'],
      passCondition: 'Navigation menu has stable selectors and is testable on mobile.',
      failCondition: 'Navigation lacks stable selectors or mobile menu is not testable.',
      notTestedMessage: 'Navigation was not tested.',
    },
    {
      id: 'cms-mobile-responsive',
      label: 'Mobile responsive layout',
      category: 'testability',
      required: true,
      evidenceSources: ['scan.selectorFindings', 'run.manifest'],
      passCondition: 'Layout adapts to mobile viewport without hiding interactive elements.',
      failCondition: 'Mobile viewport breaks layout or hides interactive elements.',
      notTestedMessage: 'Mobile responsiveness was not tested.',
    },
    {
      id: 'cms-media-accessibility',
      label: 'Media accessibility',
      category: 'accessibility',
      required: true,
      evidenceSources: ['scan.accessibilityFindings'],
      passCondition: 'All visible images have alt text or are marked decorative.',
      failCondition: 'Visible images lack alt text.',
      notTestedMessage: 'Media accessibility was not assessed.',
    },
  ],
  notTestedWarnings: [
    'CMS admin panel and publishing workflow are not tested unless specific templates exist.',
    'Real content publishing is not tested.',
    'Analytics and tracking scripts are noted but not tested.',
    'SEO metadata beyond page title is not tested.',
    'User-generated content moderation is not tested.',
  ],
  policyFocus: [
    'Block destructive content deletion actions.',
    'Block real email newsletter sending.',
    'Block contact form submission to real recipients.',
  ],
  accessibilityFocus: [
    'All images must have alt text.',
    'Navigation must be keyboard-accessible.',
    'Form inputs must have labels.',
    'Focus indicators must be visible.',
  ],
  securityFocus: [
    'No real visitor data in test artifacts.',
    'No analytics keys or tracking IDs in logs.',
    'No contact form submission to real addresses.',
  ],
  dataSafetyFocus: [
    'All test data uses forgeqa.test domains only.',
    'No real subscriber emails in test data.',
    'No real contact form submissions.',
  ],
  reportLanguage: 'en',
  readinessCriteria: [
    {
      id: 'cms-nav-ready',
      label: 'Navigation testable',
      category: 'testability',
      required: true,
      evidenceSources: ['scan.selectorFindings'],
      passCondition: 'Navigation has stable selectors on desktop and mobile.',
      failCondition: 'Navigation lacks stable selectors or mobile menu is missing.',
      notTestedMessage: 'Navigation readiness was not assessed.',
    },
    {
      id: 'cms-images-ready',
      label: 'Images accessible',
      category: 'accessibility',
      required: true,
      evidenceSources: ['scan.accessibilityFindings'],
      passCondition: 'All visible images have alt attributes.',
      failCondition: 'Visible images lack alt attributes.',
      notTestedMessage: 'Image accessibility was not assessed.',
    },
    {
      id: 'cms-external-assets',
      label: 'External assets documented',
      category: 'testability',
      required: false,
      evidenceSources: ['scan.externalAssetFindings'],
      passCondition: 'External assets are documented and do not cause flakiness.',
      failCondition: 'External assets cause page load flakiness.',
      notTestedMessage: 'External asset readiness was not assessed.',
    },
  ],
  caveats: [
    'This pack evaluates QA readiness, not SEO performance or content strategy.',
    'This is not a legal, regulatory, or compliance certification.',
    'CMS backend and publishing workflows are outside scope.',
    'Third-party integrations (analytics, ads) are noted but not tested.',
  ],
  references: [
    'ForgeQA Scanner: accessibility, external asset, and selector checks',
    'ForgeQA Policy: contact form and destructive action blocking',
    'ForgeQA Templates: mobile responsive, pagination, diagnostics',
  ],
};
