import type { IndustryPack } from '../types.js';

export const ecommerceCheckoutSafePack: IndustryPack = {
  id: 'ecommerce-checkout-safe',
  name: 'Ecommerce / Checkout (Safe Mode)',
  version: '1.0.0',
  description:
    'Readiness pack for ecommerce and checkout-style apps in safe mode only. Focuses on catalog search, product page structure, and policy blocks for real payment execution.',
  appCategory: 'Ecommerce / Online Store',
  targetUsers: ['shopper', 'merchant', 'admin'],
  riskLevel: 'high',
  recommendedTemplates: [
    {
      templateId: 'generic.paginationAndSearch',
      priority: 'required',
      reason: 'Ecommerce apps rely heavily on catalog search and product filtering.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.mobileResponsiveCheck',
      priority: 'required',
      reason: 'Shoppers primarily browse on mobile devices.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'policy.paymentFlowGate',
      priority: 'required',
      reason: 'Payment fields and checkout buttons must be detected and blocked by policy.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'diagnostic.mediaAccessibility',
      priority: 'recommended',
      reason: 'Product images must have alt text for accessibility and SEO.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'diagnostic.missingLabel',
      priority: 'recommended',
      reason: 'Checkout and contact forms must have labeled inputs.',
      appliesToModes: ['both'],
    },
  ],
  optionalTemplates: [
    {
      templateId: 'generic.multiStepFormValidation',
      priority: 'optional',
      reason: 'Useful if the checkout is a multi-step wizard.',
      appliesToModes: ['both'],
    },
  ],
  blockedTemplates: [
    'generic.alumniRegistration',
    'generic.passwordResetRequest',
    'generic.fileUploadWithPreview',
  ],
  scannerFocus: [
    'catalog search and filter selectors',
    'product card/list selectors',
    'product image alt text',
    'cart UI elements (noted, not tested)',
    'payment input detection (blocked)',
    'checkout button detection (blocked)',
    'external payment script detection',
  ],
  requiredScopeItems: [
    {
      id: 'ecom-catalog-search',
      label: 'Catalog search and pagination',
      category: 'navigation',
      required: true,
      evidenceSources: ['scan.selectorFindings', 'run.manifest'],
      passCondition: 'Search input and product table/grid present with stable selectors.',
      failCondition: 'No search input or no stable selectors for product grid.',
      notTestedMessage: 'Catalog search and pagination were not tested.',
    },
    {
      id: 'ecom-payment-blocked',
      label: 'Payment actions blocked by policy',
      category: 'policy',
      required: true,
      evidenceSources: ['scan.riskFindings', 'run.policyDecisions'],
      passCondition: 'Payment fields and checkout buttons detected and blocked by policy.',
      failCondition: 'Payment fields present but policy did not block them.',
      notTestedMessage: 'Payment action policy gate was not assessed.',
    },
    {
      id: 'ecom-product-images',
      label: 'Product image accessibility',
      category: 'accessibility',
      required: true,
      evidenceSources: ['scan.accessibilityFindings'],
      passCondition: 'Product images have alt text or are marked decorative.',
      failCondition: 'Product images lack alt text.',
      notTestedMessage: 'Product image accessibility was not assessed.',
    },
  ],
  notTestedWarnings: [
    'Cart add/remove/update is noted as not tested unless a specific template exists.',
    'Real checkout flow and payment authorization are explicitly blocked and not tested.',
    'Shipping address validation is not tested.',
    'Order history and refunds are not tested.',
    'Inventory management is not tested.',
    'Real payment execution is never performed by ForgeQA.',
  ],
  policyFocus: [
    'Block all payment input fields.',
    'Block all checkout/subscribe/purchase buttons.',
    'Block external payment scripts (Stripe, PayPal, etc).',
    'Block real card data entry.',
  ],
  accessibilityFocus: [
    'Product images must have alt text.',
    'Search inputs must have labels.',
    'Form inputs in checkout must be labeled.',
  ],
  securityFocus: [
    'No real payment data in test artifacts.',
    'No card numbers, CVV, or billing info in generated data.',
    'No real checkout execution.',
  ],
  dataSafetyFocus: [
    'No real customer data in generated test users.',
    'No real addresses or phone numbers in test data.',
    'All test data uses approved test domains only.',
  ],
  reportLanguage: 'en',
  readinessCriteria: [
    {
      id: 'ecom-search-ready',
      label: 'Catalog search testable',
      category: 'testability',
      required: true,
      evidenceSources: ['scan.selectorFindings'],
      passCondition: 'Search input and product grid have stable selectors.',
      failCondition: 'Search or product grid lacks stable selectors.',
      notTestedMessage: 'Catalog search readiness was not assessed.',
    },
    {
      id: 'ecom-payment-policy',
      label: 'Payment blocked by policy',
      category: 'policy',
      required: true,
      evidenceSources: ['scan.riskFindings', 'run.policyDecisions'],
      passCondition: 'Payment fields detected and blocked by ForgeQA policy.',
      failCondition: 'Payment fields present but not blocked by policy.',
      notTestedMessage: 'Payment policy readiness was not assessed.',
    },
    {
      id: 'ecom-images-accessible',
      label: 'Product images accessible',
      category: 'accessibility',
      required: true,
      evidenceSources: ['scan.accessibilityFindings'],
      passCondition: 'All visible images have alt attributes.',
      failCondition: 'Visible images lack alt attributes.',
      notTestedMessage: 'Image accessibility was not assessed.',
    },
  ],
  caveats: [
    'This pack evaluates QA readiness, not PCI-DSS compliance or payment security.',
    'This is not a legal, regulatory, or compliance certification.',
    'Real payment flows are never executed by ForgeQA.',
    'Third-party payment provider integration is outside scope.',
  ],
  references: [
    'ForgeQA Scanner: risk and accessibility checks',
    'ForgeQA Policy: payment action blocking',
    'ForgeQA Templates: pagination, mobile responsive, policy gates',
  ],
};
