import type { IndustryPack } from '../types.js';

export const educationAlumniPack: IndustryPack = {
  id: 'education-alumni',
  name: 'Education / Alumni Portal',
  version: '1.0.0',
  description:
    'Readiness pack for alumni, student, and education community platforms. Covers registration, profile completeness, file upload, search, password reset, and data safety.',
  appCategory: 'Education / Community Platform',
  targetUsers: ['student', 'alumni', 'faculty', 'admin'],
  riskLevel: 'medium',
  recommendedTemplates: [
    {
      templateId: 'forgecircle.registerAlumniCompleteProfile',
      priority: 'required',
      reason: 'Core registration and profile flow for education platforms.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.passwordResetRequest',
      priority: 'required',
      reason: 'Password reset is a critical user journey in education platforms.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.fileUploadWithPreview',
      priority: 'required',
      reason: 'Avatar and document uploads are common in alumni profiles.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.paginationAndSearch',
      priority: 'recommended',
      reason: 'Alumni directories and student search require table/pagination coverage.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.mobileResponsiveCheck',
      priority: 'recommended',
      reason: 'Students and alumni access portals from mobile devices.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.multiStepFormValidation',
      priority: 'recommended',
      reason: 'Multi-step registration and profile forms benefit from validation testing.',
      appliesToModes: ['both'],
    },
  ],
  optionalTemplates: [
    {
      templateId: 'policy.destructiveActionGate',
      priority: 'optional',
      reason: 'Useful if admin deletion of student/alumni records is present.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'policy.paymentFlowGate',
      priority: 'optional',
      reason: 'Relevant if the platform has donation or fee payment flows.',
      appliesToModes: ['both'],
    },
  ],
  blockedTemplates: [],
  scannerFocus: [
    'registration form selectors and labels',
    'profile form completeness indicators',
    'file upload inputs with data-testid',
    'search/directory table selectors',
    'password reset form accessibility',
    'mobile navigation elements',
  ],
  requiredScopeItems: [
    {
      id: 'edu-registration',
      label: 'Registration / profile creation',
      category: 'forms',
      required: true,
      evidenceSources: ['scan.formFindings', 'run.manifest'],
      passCondition: 'Registration form present with stable selectors and labeled inputs.',
      failCondition: 'Registration form lacks labels or stable selectors.',
      notTestedMessage: 'Registration/profile flow was not tested.',
    },
    {
      id: 'edu-file-upload',
      label: 'File upload (avatar/document)',
      category: 'forms',
      required: true,
      evidenceSources: ['scan.formFindings', 'run.manifest'],
      passCondition: 'File input present and testable with generated safe files.',
      failCondition: 'File input lacks data-testid or safe upload path.',
      notTestedMessage: 'File upload was not tested.',
    },
    {
      id: 'edu-password-reset',
      label: 'Password reset request',
      category: 'security',
      required: true,
      evidenceSources: ['run.manifest'],
      passCondition: 'Password reset template executed successfully.',
      failCondition: 'Password reset template failed or was not run.',
      notTestedMessage: 'Password reset was not tested.',
    },
  ],
  notTestedWarnings: [
    'Messaging between students/alumni is not tested unless a messaging template exists.',
    'Events and job boards are not tested unless specific templates exist.',
    'Admin approval workflows are not tested unless specific templates exist.',
    'Real student data must never be used in ForgeQA tests.',
  ],
  policyFocus: [
    'Block destructive actions on student/alumni records.',
    'Block real email sending to students/alumni.',
    'Block payment/donation flows unless explicitly approved.',
  ],
  accessibilityFocus: [
    'All registration and profile forms must have labeled inputs.',
    'Upload controls must have accessible names.',
    'Navigation must be keyboard-accessible.',
  ],
  securityFocus: [
    'No real student emails or passwords in test data.',
    'No real PII in screenshots or artifacts.',
    'No destructive actions on real records.',
  ],
  dataSafetyFocus: [
    'All test data uses forgeqa.test domains only.',
    'Generated users are tagged createdByForgeQA=true and safeToDelete=true.',
    'No real student/alumni data is collected or stored.',
  ],
  reportLanguage: 'en',
  readinessCriteria: [
    {
      id: 'edu-registration-ready',
      label: 'Registration flow testable',
      category: 'testability',
      required: true,
      evidenceSources: ['scan.formFindings', 'scan.selectorFindings'],
      passCondition: 'Registration form has stable selectors and labeled inputs.',
      failCondition: 'Registration form lacks stable selectors or labels.',
      notTestedMessage: 'Registration flow readiness was not assessed.',
    },
    {
      id: 'edu-upload-ready',
      label: 'File upload testable',
      category: 'testability',
      required: true,
      evidenceSources: ['scan.formFindings'],
      passCondition: 'File input has data-testid and is testable with generated files.',
      failCondition: 'File input missing or lacks stable selector.',
      notTestedMessage: 'File upload readiness was not assessed.',
    },
    {
      id: 'edu-data-safety',
      label: 'No real student data used',
      category: 'data-safety',
      required: true,
      evidenceSources: ['data-safety-audit'],
      passCondition: 'All generated data uses approved test domains.',
      failCondition: 'Real student data or external domain detected in test data.',
      notTestedMessage: 'Data safety was not audited.',
    },
  ],
  caveats: [
    'This pack evaluates QA readiness, not application security or FERPA compliance.',
    'This is not a legal, regulatory, or compliance certification.',
    'Role-based access for students vs alumni vs faculty is not automatically tested.',
    'Third-party integrations (LMS, CRM) are outside scope.',
  ],
  references: [
    'ForgeQA Scanner: form, upload, and accessibility checks',
    'ForgeQA Data Safety: test domain and safeToDelete requirements',
    'ForgeQA Templates: alumni registration, password reset, file upload, pagination',
  ],
};
