import type { IndustryPack } from '../types.js';

export const genericSaasAdminPack: IndustryPack = {
  id: 'generic-saas-admin',
  name: 'Generic SaaS Admin Dashboard',
  version: '1.0.0',
  description:
    'Readiness pack for SaaS admin dashboards and management panels. Focuses on navigation stability, table interactions, form validation, dangerous admin actions, and accessibility.',
  appCategory: 'SaaS / Admin Dashboard',
  targetUsers: ['admin', 'moderator', 'operator'],
  riskLevel: 'medium',
  recommendedTemplates: [
    {
      templateId: 'generic.paginationAndSearch',
      priority: 'required',
      reason: 'Admin dashboards almost always include tables with search and pagination.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.multiStepFormValidation',
      priority: 'required',
      reason: 'Admin forms (create user, edit settings) require validation coverage.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.mobileResponsiveCheck',
      priority: 'recommended',
      reason: 'Admins may access dashboards from tablets and mobile devices.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'policy.destructiveActionGate',
      priority: 'required',
      reason: 'Admin panels often contain delete/archive/bulk actions that must be gated by policy.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'diagnostic.missingLabel',
      priority: 'recommended',
      reason: 'Admin forms must be accessible for automation reliability.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'diagnostic.duplicateTestId',
      priority: 'recommended',
      reason: 'Admin UIs with many repeated rows risk duplicate test IDs.',
      appliesToModes: ['both'],
    },
  ],
  optionalTemplates: [
    {
      templateId: 'generic.fileUploadWithPreview',
      priority: 'optional',
      reason: 'Useful if the admin panel supports avatar/logo/document upload.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.passwordResetRequest',
      priority: 'optional',
      reason: 'Relevant if the admin panel manages user passwords.',
      appliesToModes: ['both'],
    },
  ],
  blockedTemplates: [],
  scannerFocus: [
    'selector readiness (data-testid on tables, buttons, forms)',
    'duplicate IDs in repeated table rows',
    'form labels and accessibility',
    'dangerous button text (delete, remove, archive)',
    'submit actions in forms',
    'file inputs if present',
  ],
  requiredScopeItems: [
    {
      id: 'admin-table-search',
      label: 'Table search and pagination',
      category: 'navigation',
      required: true,
      evidenceSources: ['scan.selectorFindings', 'run.manifest'],
      passCondition: 'Table with search input and pagination controls present and testable.',
      failCondition: 'No table or no stable selectors for search/pagination.',
      notTestedMessage: 'Table search and pagination were not covered by any executed template.',
    },
    {
      id: 'admin-form-validation',
      label: 'Form validation',
      category: 'forms',
      required: true,
      evidenceSources: ['scan.formFindings', 'run.manifest'],
      passCondition: 'Forms present with stable selectors and validation messages.',
      failCondition: 'Forms lack labels, test IDs, or validation message regions.',
      notTestedMessage: 'No form validation template was executed.',
    },
    {
      id: 'admin-destructive-gate',
      label: 'Destructive action policy gate',
      category: 'policy',
      required: true,
      evidenceSources: ['scan.riskFindings', 'run.policyDecisions'],
      passCondition: 'Destructive actions detected and blocked by policy.',
      failCondition: 'Destructive actions present but not blocked by policy.',
      notTestedMessage: 'No destructive action policy gate template was executed.',
    },
  ],
  notTestedWarnings: [
    'Login/auth flow is noted as not tested unless an explicit auth template exists.',
    'Bulk data export/import is not tested unless a specific template exists.',
    'Real user provisioning/de-provisioning is not tested.',
    'Third-party integrations are not tested.',
  ],
  policyFocus: [
    'Block destructive admin actions (delete, remove, archive, purge).',
    'Block bulk actions that affect many records.',
    'Block real data export to external systems.',
  ],
  accessibilityFocus: [
    'All admin forms must have labeled inputs.',
    'Table headers must be semantically correct.',
    'Buttons must have accessible names.',
  ],
  securityFocus: [
    'No real credential handling in automation.',
    'No destructive actions executed.',
    'No real user data in generated test data.',
  ],
  dataSafetyFocus: [
    'All generated test data uses approved test domains only.',
    'No real user emails or passwords in artifacts.',
  ],
  reportLanguage: 'en',
  readinessCriteria: [
    {
      id: 'stable-selectors',
      label: 'Stable selectors for admin UI',
      category: 'testability',
      required: true,
      evidenceSources: ['scan.selectorFindings'],
      passCondition: 'Interactive elements have data-testid or stable IDs.',
      failCondition: 'Many interactive elements lack stable selectors.',
      notTestedMessage: 'Selector readiness was not assessed.',
    },
    {
      id: 'form-accessibility',
      label: 'Form accessibility',
      category: 'accessibility',
      required: true,
      evidenceSources: ['scan.accessibilityFindings'],
      passCondition: 'All visible inputs have labels.',
      failCondition: 'Unlabeled inputs detected.',
      notTestedMessage: 'Form accessibility was not assessed.',
    },
    {
      id: 'destructive-actions-blocked',
      label: 'Destructive actions blocked',
      category: 'policy',
      required: true,
      evidenceSources: ['scan.riskFindings', 'run.policyDecisions'],
      passCondition: 'Destructive actions are detected and policy blocks them.',
      failCondition: 'Destructive actions present and not blocked.',
      notTestedMessage: 'Destructive action policy was not assessed.',
    },
  ],
  caveats: [
    'This pack evaluates QA readiness, not application security.',
    'This is not a legal, regulatory, or compliance certification.',
    'Admin-specific behaviors (role-based access) are not automatically tested.',
    'Third-party admin integrations are outside scope.',
  ],
  references: [
    'ForgeQA Scanner: data-testid and accessibility checks',
    'ForgeQA Policy: destructive action blocking',
    'ForgeQA Templates: pagination, forms, mobile responsive, policy gates',
  ],
};
