import type { IndustryPack } from '../types.js';

export const healthcareAppointmentSafePack: IndustryPack = {
  id: 'healthcare-appointment-safe',
  name: 'Healthcare / Appointment (Safe Mode)',
  version: '1.0.0',
  description:
    'Readiness pack for clinic and healthcare appointment apps in safe mode only. Focuses on appointment forms, contact forms, file upload, PHI warnings, and data privacy.',
  appCategory: 'Healthcare / Clinic / Appointment',
  targetUsers: ['patient', 'provider', 'admin'],
  riskLevel: 'high',
  recommendedTemplates: [
    {
      templateId: 'generic.multiStepFormValidation',
      priority: 'required',
      reason: 'Appointment booking and patient intake are typically multi-step forms.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.fileUploadWithPreview',
      priority: 'recommended',
      reason: 'Healthcare apps may require document or image uploads.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.passwordResetRequest',
      priority: 'recommended',
      reason: 'Patient portals require password reset capability.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'generic.mobileResponsiveCheck',
      priority: 'required',
      reason: 'Patients often book appointments from mobile devices.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'diagnostic.missingLabel',
      priority: 'required',
      reason: 'Healthcare forms must have clear labels for accessibility and legal safety.',
      appliesToModes: ['both'],
    },
    {
      templateId: 'diagnostic.mediaAccessibility',
      priority: 'recommended',
      reason: 'Images and diagrams in healthcare apps should have alt text.',
      appliesToModes: ['both'],
    },
  ],
  optionalTemplates: [
    {
      templateId: 'policy.destructiveActionGate',
      priority: 'optional',
      reason: 'Relevant if admin can delete patient records.',
      appliesToModes: ['both'],
    },
  ],
  blockedTemplates: [
    'generic.alumniRegistration',
  ],
  scannerFocus: [
    'appointment form selectors and labels',
    'contact form selectors',
    'file upload inputs for documents/images',
    'patient data input fields (warn, do not test with real data)',
    'accessibility of instructions and labels',
    'mobile layout of forms',
  ],
  requiredScopeItems: [
    {
      id: 'health-form-validation',
      label: 'Appointment / intake form validation',
      category: 'forms',
      required: true,
      evidenceSources: ['scan.formFindings', 'run.manifest'],
      passCondition: 'Forms present with stable selectors, labeled inputs, and validation messages.',
      failCondition: 'Forms lack labels or stable selectors.',
      notTestedMessage: 'Appointment/intake form validation was not tested.',
    },
    {
      id: 'health-mobile-responsive',
      label: 'Mobile responsive forms',
      category: 'testability',
      required: true,
      evidenceSources: ['scan.selectorFindings', 'run.manifest'],
      passCondition: 'Forms are accessible and testable on mobile viewport.',
      failCondition: 'Mobile viewport hides or breaks form elements.',
      notTestedMessage: 'Mobile responsiveness was not tested.',
    },
    {
      id: 'health-data-safety',
      label: 'No real patient data in tests',
      category: 'data-safety',
      required: true,
      evidenceSources: ['data-safety-audit', 'scan.riskFindings'],
      passCondition: 'No real patient names, emails, or PHI in test data or artifacts.',
      failCondition: 'Real patient data or PHI-like fields detected in test data.',
      notTestedMessage: 'Data safety audit was not performed.',
    },
  ],
  notTestedWarnings: [
    'Real appointment booking with a live system is not tested.',
    'Patient portal authentication is not tested unless an auth template exists.',
    'Medical record viewing/editing is not tested.',
    'Insurance verification is not tested.',
    'Prescription management is not tested.',
    'Real patient data must never be used in ForgeQA tests.',
  ],
  policyFocus: [
    'Block destructive actions on patient records.',
    'Block real email sending to patients.',
    'Block any action that could modify real appointment data.',
  ],
  accessibilityFocus: [
    'All form inputs must have clear labels and instructions.',
    'Error messages must be descriptive and accessible.',
    'Color alone must not convey critical health information.',
  ],
  securityFocus: [
    'No real patient data in generated test users.',
    'No real medical record numbers or insurance IDs in test data.',
    'No real appointment scheduling against live systems.',
  ],
  dataSafetyFocus: [
    'All test data uses forgeqa.test domains only.',
    'Generated users are tagged createdByForgeQA=true and safeToDelete=true.',
    'No PHI or real patient information in artifacts.',
  ],
  reportLanguage: 'en',
  readinessCriteria: [
    {
      id: 'health-form-ready',
      label: 'Appointment forms testable',
      category: 'testability',
      required: true,
      evidenceSources: ['scan.formFindings', 'scan.selectorFindings'],
      passCondition: 'Appointment forms have stable selectors and labeled inputs.',
      failCondition: 'Forms lack stable selectors or labels.',
      notTestedMessage: 'Appointment form readiness was not assessed.',
    },
    {
      id: 'health-phi-warning',
      label: 'PHI risk acknowledged',
      category: 'data-safety',
      required: true,
      evidenceSources: ['scan.riskFindings', 'data-safety-audit'],
      passCondition: 'No real patient data detected; all test data is synthetic.',
      failCondition: 'Real patient-like data or PHI fields detected in test artifacts.',
      notTestedMessage: 'PHI risk was not assessed.',
    },
    {
      id: 'health-mobile-ready',
      label: 'Mobile responsive',
      category: 'testability',
      required: true,
      evidenceSources: ['scan.selectorFindings'],
      passCondition: 'Forms and navigation are testable on mobile viewport.',
      failCondition: 'Mobile viewport hides or breaks interactive elements.',
      notTestedMessage: 'Mobile readiness was not assessed.',
    },
  ],
  caveats: [
    'This pack evaluates QA readiness, not HIPAA compliance or clinical safety.',
    'This is not a legal, regulatory, or compliance certification.',
    'Real patient data must never be used in ForgeQA tests.',
    'Live appointment booking is never performed by ForgeQA.',
    'Clinical decision support is outside scope.',
  ],
  references: [
    'ForgeQA Scanner: form, accessibility, and risk checks',
    'ForgeQA Data Safety: test domain and safeToDelete requirements',
    'ForgeQA Policy: destructive action and data safety blocking',
  ],
};
