import type { AppTestabilityScan, ScannerSeverity } from './types.js';
import type { TemplateRecommendation } from './template-recommender.js';

function severityIcon(sev: ScannerSeverity): string {
  switch (sev) {
    case 'critical': return '❌';
    case 'error': return '🔴';
    case 'warning': return '🟡';
    case 'info': return '🔵';
    default: return '';
  }
}

export function generateScanMarkdown(scan: AppTestabilityScan, recommendations?: TemplateRecommendation[]): string {
  const lines: string[] = [];
  lines.push('# ForgeQA App Testability Scan Report');
  lines.push('');
  lines.push(`- **Scan ID:** \`${scan.scanId}\``);
  lines.push(`- **Target URL:** ${scan.targetUrl}`);
  lines.push(`- **Mode:** ${scan.mode}`);
  lines.push(`- **Status:** ${scan.status}`);
  lines.push(`- **Created At:** ${scan.createdAt}`);
  lines.push('');

  lines.push('## Executive Summary');
  lines.push('');
  lines.push(`- **Overall Testability Score:** ${scan.score.overall}/100`);
  lines.push(`- **Selector Score:** ${scan.score.selectorScore}/100`);
  lines.push(`- **Accessibility Score:** ${scan.score.accessibilityScore}/100`);
  lines.push(`- **Form Score:** ${scan.score.formScore}/100`);
  lines.push(`- **Risk Score:** ${scan.score.riskScore}/100`);
  lines.push(`- **Total Findings:** ${scan.summary.totalFindings}`);
  lines.push(`  - Critical: ${scan.summary.criticalCount}`);
  lines.push(`  - Error: ${scan.summary.errorCount}`);
  lines.push(`  - Warning: ${scan.summary.warningCount}`);
  lines.push(`  - Info: ${scan.summary.infoCount}`);
  lines.push('');

  lines.push('## Recommendations');
  lines.push('');
  for (const rec of scan.recommendations) {
    lines.push(`- ${rec}`);
  }
  lines.push('');

  if (recommendations && recommendations.length > 0) {
    lines.push('## Suggested ForgeQA Templates');
    lines.push('');
    for (const rec of recommendations) {
      lines.push(`- **${rec.templateName}** (${rec.confidence} confidence)`);
      lines.push(`  - ${rec.reason}`);
    }
    lines.push('');
  }

  lines.push('## Findings');
  lines.push('');
  for (const finding of scan.findings) {
    lines.push(`### ${severityIcon(finding.severity)} ${finding.title}`);
    lines.push(`- **Category:** ${finding.category}`);
    lines.push(`- **Severity:** ${finding.severity}`);
    lines.push(`- **Confidence:** ${finding.confidence}`);
    lines.push(`- **Message:** ${finding.message}`);
    if (finding.evidence) lines.push(`- **Evidence:** ${finding.evidence}`);
    if (finding.selectorHint) lines.push(`- **Selector Hint:** \`${finding.selectorHint}\``);
    lines.push(`- **Suggested Fix:** ${finding.suggestedFix}`);
    if (finding.relatedPatternId) lines.push(`- **Related Pattern:** ${finding.relatedPatternId}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('*This scan was generated by ForgeQA App Testability Scanner. It is read-only and did not mutate the target page.*');
  lines.push('');

  return lines.join('\n');
}

export function generateScanHtml(scan: AppTestabilityScan, recommendations?: TemplateRecommendation[]): string {
  const lines: string[] = [];
  lines.push(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ForgeQA Testability Scan — ${scan.scanId}</title>
<style>
  body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.5; padding: 24px; max-width: 960px; margin: 0 auto; color: #333; }
  h1 { font-size: 1.5rem; border-bottom: 2px solid #ddd; padding-bottom: 8px; }
  h2 { font-size: 1.2rem; margin-top: 24px; }
  h3 { font-size: 1rem; margin-top: 16px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8rem; font-weight: 600; }
  .badge-critical { background: #ffebee; color: #c62828; }
  .badge-error { background: #fff3e0; color: #ef6c00; }
  .badge-warning { background: #fffde7; color: #f9a825; }
  .badge-info { background: #e3f2fd; color: #1565c0; }
  .status-pass { color: #2e7d32; }
  .status-warn { color: #f9a825; }
  .status-fail { color: #c62828; }
  .status-review { color: #6a1b9a; }
  table { border-collapse: collapse; width: 100%; margin-top: 8px; }
  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
  th { background: #f5f5f5; }
  .finding { border: 1px solid #ddd; border-radius: 6px; padding: 12px; margin: 8px 0; }
</style>
</head>
<body>
<h1>ForgeQA App Testability Scan</h1>
<p><strong>Scan ID:</strong> <code>${scan.scanId}</code></p>
<p><strong>Target URL:</strong> <code>${scan.targetUrl}</code></p>
<p><strong>Mode:</strong> ${scan.mode}</p>
<p><strong>Status:</strong> <span class="status-${scan.status}">${scan.status}</span></p>
<p><strong>Created At:</strong> ${scan.createdAt}</p>

<h2>Score</h2>
<table>
<tr><th>Category</th><th>Score</th></tr>
<tr><td>Overall</td><td><strong>${scan.score.overall}</strong>/100</td></tr>
<tr><td>Selector</td><td>${scan.score.selectorScore}/100</td></tr>
<tr><td>Accessibility</td><td>${scan.score.accessibilityScore}/100</td></tr>
<tr><td>Form</td><td>${scan.score.formScore}/100</td></tr>
<tr><td>Risk</td><td>${scan.score.riskScore}/100</td></tr>
<tr><td>Route</td><td>${scan.score.routeScore}/100</td></tr>
</table>

<h2>Summary</h2>
<table>
<tr><th>Total</th><th>Critical</th><th>Error</th><th>Warning</th><th>Info</th></tr>
<tr><td>${scan.summary.totalFindings}</td><td>${scan.summary.criticalCount}</td><td>${scan.summary.errorCount}</td><td>${scan.summary.warningCount}</td><td>${scan.summary.infoCount}</td></tr>
</table>

<h2>Recommendations</h2>
<ul>
${scan.recommendations.map((r) => `<li>${escapeHtml(r)}</li>`).join('\n')}
</ul>
`);

  if (recommendations && recommendations.length > 0) {
    lines.push(`<h2>Suggested Templates</h2>
<ul>
${recommendations.map((rec) => `<li><strong>${escapeHtml(rec.templateName)}</strong> (${rec.confidence}) — ${escapeHtml(rec.reason)}</li>`).join('\n')}
</ul>
`);
  }

  lines.push(`<h2>Findings</h2>
`);

  for (const finding of scan.findings) {
    const sevClass = `badge-${finding.severity}`;
    lines.push(`<div class="finding">
<h3><span class="badge ${sevClass}">${finding.severity.toUpperCase()}</span> ${escapeHtml(finding.title)}</h3>
<p><strong>Category:</strong> ${finding.category}</p>
<p><strong>Confidence:</strong> ${finding.confidence}</p>
<p>${escapeHtml(finding.message)}</p>
${finding.evidence ? `<p><strong>Evidence:</strong> <code>${escapeHtml(finding.evidence)}</code></p>` : ''}
${finding.selectorHint ? `<p><strong>Selector:</strong> <code>${escapeHtml(finding.selectorHint)}</code></p>` : ''}
<p><strong>Fix:</strong> ${escapeHtml(finding.suggestedFix)}</p>
${finding.relatedPatternId ? `<p><strong>Pattern:</strong> ${finding.relatedPatternId}</p>` : ''}
</div>
`);
  }

  lines.push(`<p><em>This scan was generated by ForgeQA App Testability Scanner. It is read-only and did not mutate the target page.</em></p>
</body>
</html>`);

  return lines.join('');
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
