import type { GoldenDataSet, CleanupReport, CleanupItem } from '../schemas/core.js';

export function analyzeCleanup(data: GoldenDataSet): CleanupReport {
  const items: CleanupItem[] = [];

  for (const user of data.users) {
    const isSafe = user.createdByForgeQA === true && user.safeToDelete === true;
    items.push({
      id: `user-${user.username}`,
      type: 'user',
      identifier: `${user.displayName} <${user.email}>`,
      safeToDelete: user.safeToDelete,
      wouldDelete: isSafe,
      reason: isSafe
        ? 'Tagged safeToDelete by ForgeQA'
        : 'Missing safety tags — skipped',
    });
  }

  for (const file of data.files) {
    const isSafe = file.createdByForgeQA === true && file.safeToDelete === true;
    items.push({
      id: `file-${file.filename}`,
      type: 'file',
      identifier: file.filename,
      safeToDelete: file.safeToDelete,
      wouldDelete: isSafe,
      reason: isSafe
        ? 'Tagged safeToDelete by ForgeQA'
        : 'Missing safety tags — skipped',
    });
  }

  // Forms
  for (let i = 0; i < (data.forms?.length ?? 0); i++) {
    items.push({
      id: `form-${i}`,
      type: 'form',
      identifier: `Form ${i + 1}`,
      safeToDelete: true,
      wouldDelete: true,
      reason: 'Tagged safeToDelete by ForgeQA',
    });
  }

  // Table records
  for (let i = 0; i < (data.tableRecords?.length ?? 0); i++) {
    items.push({
      id: `record-${i}`,
      type: 'table-record',
      identifier: `Table record ${i + 1}`,
      safeToDelete: true,
      wouldDelete: true,
      reason: 'Tagged safeToDelete by ForgeQA',
    });
  }

  const safe = items.filter((i) => i.safeToDelete).length;
  const unsafe = items.filter((i) => !i.safeToDelete).length;
  const wouldDelete = items.filter((i) => i.wouldDelete).length;

  return {
    runId: data.runId,
    e2eRunId: data.e2eRunId,
    generatedAt: new Date().toISOString(),
    dryRun: true,
    items,
    summary: {
      total: items.length,
      safe,
      unsafe,
      wouldDelete,
    },
  };
}

export function generateCleanupMarkdown(report: CleanupReport): string {
  const lines: string[] = [];

  lines.push('# ForgeQA Cleanup Dry-Run Report');
  lines.push('');

  lines.push('## Run Identification');
  lines.push('');
  lines.push(`- **Run ID:** \`${report.runId}\``);
  lines.push(`- **E2E Run ID:** \`${report.e2eRunId}\``);
  lines.push(`- **Generated:** ${report.generatedAt}`);
  lines.push('');

  lines.push('## Dry-Run Status');
  lines.push('');
  lines.push('**DRY-RUN ONLY** — No items were deleted.');
  lines.push('');

  lines.push('## Golden Data v2 Summary');
  lines.push('');
  lines.push(`- **Total items reviewed:** ${report.summary.total}`);
  lines.push(`- **Users:** ${report.items.filter((i) => i.type === 'user').length}`);
  lines.push(`- **Files:** ${report.items.filter((i) => i.type === 'file').length}`);
  lines.push(`- **Forms:** ${report.items.filter((i) => i.type === 'form').length}`);
  lines.push(`- **Table records:** ${report.items.filter((i) => i.type === 'table-record').length}`);
  lines.push(`- **Safe to delete:** ${report.summary.safe}`);
  lines.push(`- **Unsafe / skipped:** ${report.summary.unsafe}`);
  lines.push(`- **Would be deleted in real run:** ${report.summary.wouldDelete}`);
  lines.push('');

  lines.push('## Items That Would Be Cleaned');
  lines.push('');
  const wouldDeleteItems = report.items.filter((i) => i.wouldDelete);
  if (wouldDeleteItems.length === 0) {
    lines.push('*No items would be cleaned.*');
  } else {
    for (const item of wouldDeleteItems) {
      lines.push(`- **${item.type.toUpperCase()}** — \`${item.identifier}\` — ${item.reason}`);
    }
  }
  lines.push('');

  lines.push('## Items Skipped');
  lines.push('');
  const skippedItems = report.items.filter((i) => !i.wouldDelete);
  if (skippedItems.length === 0) {
    lines.push('*No items were skipped.*');
  } else {
    for (const item of skippedItems) {
      lines.push(`- **${item.type.toUpperCase()}** — \`${item.identifier}\` — ${item.reason}`);
    }
  }
  lines.push('');

  lines.push('## Safety Checks');
  lines.push('');
  lines.push(`- All items have \`createdByForgeQA=true\`: ${report.items.every((i) => i.safeToDelete) ? 'Yes' : 'No'}`);
  lines.push(`- All items have \`safeToDelete=true\`: ${report.items.every((i) => i.safeToDelete) ? 'Yes' : 'No'}`);
  lines.push('');

  lines.push('## Cleanup Eligibility');
  lines.push('');
  lines.push('*Cleanup remains dry-run only. No items were deleted. Every generated entity is tagged safeToDelete.*');
  lines.push('');

  lines.push('## Final Statement');
  lines.push('');
  lines.push('**No items were deleted. This was a dry-run cleanup report only.**');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*Generated by ForgeQA MVP. Do not rely on this report for production cleanup decisions without human review.*');
  lines.push('');

  return lines.join('\n');
}
